use_frameworks!

target 'JSBridge_Example' do
  pod 'OasisJSBridge', :path => '../'
  platform :ios, '9.0'

  target 'JSBridge_Tests' do
    inherit! :search_paths
    source_files = 'Tests/Sources/**/*'
    resources = 'Tests/Resources/**/*'
    pod 'OHHTTPStubs/Swift'
  end
end
